FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Python script
COPY /data/sample.csv csv_to_influxdb.py .

# Run the script
CMD ["python", "csv_to_influxdb.py"]