version: '3.8'

volumes:
  influxdb_data: {}
  # grafana_data: {}

# networks:
#   my_network:
#     driver: bridge

services:
  # InfluxDB Service
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"  # Web UI/API
    # networks:
    #   - my_network
    volumes:
      - influxdb_data:/var/lib/influxdb2  # Persistent storage
    # env_file:
    #   - .env
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin12345678
      - DOCKER_INFLUXDB_INIT_ORG=parag
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=35gU7E5TTcMfJ53zq6KIhx7Kw_IKBvRUpQN3cE8utYfqpihGTEQFCDR2XAH_8dkUougL0WZ33eqVtgRuGOu9IA==

  # # Grafana Service
  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"  # Web UI
  #   volumes:
  #     - grafana_data:/var/lib/grafana  # Persistent dashboards
  #   depends_on:
  #     - influxdb
  #   # networks:
  #   #   - my_network
  #   env_file:
  #     - .env
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  # Python CSV Loader Service
  csv_loader:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: csv_loader
    volumes:
      - ./data:/app/data  # Mount CSV files
    depends_on:
      - influxdb
    # networks:
    #   - my_network
    # env_file:
    #   - .env
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=35gU7E5TTcMfJ53zq6KIhx7Kw_IKBvRUpQN3cE8utYfqpihGTEQFCDR2XAH_8dkUougL0WZ33eqVtgRuGOu9IA==
      - INFLUXDB_ORG=parag
      - INFLUXDB_BUCKET=mybucket
    restart: on-failure